# Generated by Django 6.0.3 on 2026-05-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_deleted_event_status_alter_event_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
    ]
