# Generated by Django 6.0.3 on 2026-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='selected_sessions',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='events.session'),
        ),
    ]
